import {test} from 'node:test';
import assert from 'node:assert/strict';
import {conceptSearch,cosine,fuseRanks} from '../lib/search';
import {records,relatedTo,collectionRecords} from '../lib/atlas';
const ids=(query:string,scope:'exact'|'near'|'theme'='near')=>conceptSearch(query,scope).results.map(r=>r.place_id);
test('new settlements retain the proper-name boundary',()=>{for(const query of ['新的定居点','新城','new town']){const found=ids(query);assert.equal(found.length,3);assert.ok(found.includes('carthage-ancient-tn'));assert.ok(!found.includes('new-york-us'));}});
test('capital and directional modifiers remain distinct',()=>{assert.equal(ids('首都','exact').length,2);assert.equal(ids('跟首都有关系的名字','near').length,5);assert.deepEqual(ids('北方的都城'),['beijing-cn']);});
test('theme scope is explicit, overlapping and non-transitive',()=>{assert.deepEqual(ids('中心','exact'),['china-cn']);assert.equal(ids('中心','theme').length,6);assert.equal(ids('名字里有新','theme').length,4);});
test('unknown water / mountain meanings do not match geography',()=>{for(const query of ['名字里有水的城市','water','黑色的城镇','mountain'])assert.equal(ids(query).length,0);});
test('name aliases and spelling tolerance',()=>{assert.equal(ids('Napoli')[0],'naples-it');assert.equal(ids('Nples')[0],'naples-it');assert.equal(ids('首尔')[0],'seoul-kr');assert.equal(ids('China')[0],'china-cn');});
test('negations are not silently inverted',()=>{assert.equal(ids('不要首都').length,0);assert.ok(conceptSearch('not a capital').notice);});
test('map strict group never links Tokyo as an unqualified capital',()=>{const seoul=records.find(r=>r.place.id==='seoul-kr')!;assert.equal(relatedTo(seoul,'exact').length,2);assert.equal(relatedTo(seoul,'near').length,5);assert.equal(collectionRecords('capital-family','exact').length,2);});
test('cosine validates vectors rather than fabricating similarity',()=>{assert.equal(cosine([1,0],[1,0]),1);assert.equal(cosine([1,0],[0,1]),0);assert.throws(()=>cosine([1],[1,0]));assert.throws(()=>cosine([0],[1]));assert.throws(()=>cosine([NaN],[1]));});
test('RRF deduplicates and keeps name matches first',()=>{const lexical=conceptSearch('Naples').results;const related=conceptSearch('新城').results;const merged=fuseRanks(lexical,related,10);assert.equal(merged[0].place_id,'naples-it');assert.equal(new Set(merged.map(r=>r.analysis_id)).size,merged.length);});
