'use client';
import {greatCircle} from '@turf/great-circle';
import workerUrl from 'maplibre-gl/dist/maplibre-gl-worker.mjs?worker&url';
import {relationLabel} from '../lib/atlas';
import {useEffect,useRef,useState} from 'react';
import type {AtlasRecord} from '../lib/atlas';
import type {Map as MapType,Marker as MarkerType} from 'maplibre-gl';
type Props={all:AtlasRecord[];visible:AtlasRecord[];selected:string|null;onSelect:(id:string)=>void;fit:number;lines:boolean};
export default function MapView({all,visible,selected,onSelect,fit,lines}:Props){
 const container=useRef<HTMLDivElement>(null),map=useRef<MapType|null>(null),markers=useRef<MarkerType[]>([]);
 const [ready,setReady]=useState(false),[failed,setFailed]=useState(false);const callback=useRef(onSelect);callback.current=onSelect;
 useEffect(()=>{let disposed=false;const timeout=setTimeout(()=>{if(!disposed)setFailed(true);},20000);import('maplibre-gl').then(lib=>{if(disposed||!container.current)return;try{
 lib.setWorkerUrl(workerUrl);
 const instance=new lib.Map({container:container.current,center:[44,29],zoom:1.55,minZoom:0.5,maxZoom:7,renderWorldCopies:false,attributionControl:false,style:{version:8,sources:{world:{type:'geojson',data:'/world.geojson'}},layers:[{id:'sea',type:'background',paint:{'background-color':'#e6edf2'}},{id:'land',type:'fill',source:'world',paint:{'fill-color':'#f8fafb'}},{id:'boundaries',type:'line',source:'world',paint:{'line-color':'#ccd7df','line-width':0.65}}]}});map.current=instance;instance.addControl(new lib.NavigationControl({showCompass:false}),'top-right');
 instance.on('load',()=>{if(disposed)return;clearTimeout(timeout);setFailed(false);const grid:any={type:'FeatureCollection',features:[]};for(let x=-180;x<=180;x+=30)grid.features.push({type:'Feature',properties:{},geometry:{type:'LineString',coordinates:[[x,-80],[x,80]]}});for(let y=-60;y<=80;y+=20)grid.features.push({type:'Feature',properties:{},geometry:{type:'LineString',coordinates:[[-180,y],[180,y]]}});instance.addSource('grid',{type:'geojson',data:grid});instance.addLayer({id:'graticule',source:'grid',type:'line',paint:{'line-color':'#a6bbc9','line-opacity':0.22,'line-width':0.7}},'land');instance.addSource('connections',{type:'geojson',data:{type:'FeatureCollection',features:[]}});instance.addLayer({id:'connections',type:'line',source:'connections',paint:{'line-color':'#4c70ca','line-width':1.5,'line-opacity':0.6,'line-dasharray':[3,3]}});setReady(true);});instance.on('error',event=>{if(String(event.error).includes('world.geojson'))setFailed(true);});}catch{setFailed(true);}}).catch(()=>setFailed(true));return()=>{disposed=true;clearTimeout(timeout);markers.current.forEach(m=>m.remove());map.current?.remove();map.current=null;};},[]);
 useEffect(()=>{if(!ready||!map.current)return;let cancelled=false;import('maplibre-gl').then(lib=>{if(cancelled||!map.current)return;markers.current.forEach(m=>m.remove());const ids=new Set(visible.map(r=>r.id));markers.current=all.map(record=>{const active=ids.has(record.id),chosen=record.id===selected;const el=document.createElement('button');el.type='button';el.className=`map-marker ${active?'is-related':''} ${chosen?'is-selected':''}`;if(active&&selected){const origin=all.find(r=>r.id===selected);if(origin&&relationLabel(origin,record)!=='同义归一'&&!chosen)el.classList.add('is-near');}el.setAttribute('aria-label',`${record.place.display_name.zh} · ${record.place.display_name.en}`);el.setAttribute('aria-pressed',String(chosen));const dot=document.createElement('span');dot.className='marker-pin';el.appendChild(dot);if(active){const label=document.createElement('span');label.className='marker-label';if(record.place.id==='carthage-ancient-tn')label.classList.add('label-below');label.textContent=record.place.display_name.en;el.appendChild(label);}el.addEventListener('click',e=>{e.stopPropagation();callback.current(record.id);});return new lib.Marker({element:el,anchor:'center'}).setLngLat(record.place.geometry.coordinates as [number,number]).addTo(map.current!);});
 const origin=all.find(r=>r.id===selected);const features=lines&&origin?visible.filter(r=>r.id!==selected).map(r=>greatCircle(origin.place.geometry.coordinates,r.place.geometry.coordinates,{npoints:64,properties:{relation:relationLabel(origin,r)}})):[];(map.current.getSource('connections') as any)?.setData({type:'FeatureCollection',features});});return()=>{cancelled=true;};},[ready,all,visible,selected,lines]);
 useEffect(()=>{if(!fit||!ready||!map.current||!visible.length)return;const xs=visible.map(r=>r.place.geometry.coordinates[0]),ys=visible.map(r=>r.place.geometry.coordinates[1]);const pad=window.innerWidth<800?65:100;map.current.fitBounds([[Math.min(...xs)-3,Math.min(...ys)-3],[Math.max(...xs)+3,Math.max(...ys)+3]],{padding:{top:100,bottom:pad,left:pad,right:window.innerWidth>1050&&selected?380:pad},maxZoom:4,duration:900});},[fit,ready]);
 return <><div ref={container} className="map-canvas" aria-label="可拖动和缩放的世界地名地图"/>{failed&&<div className="map-error" role="status">地图暂时无法加载。你仍可以在列表中浏览地名与词源。</div>}<div className="map-attribution">底图：<a href="https://www.naturalearthdata.com/about/terms-of-use/" target="_blank" rel="noreferrer">Natural Earth</a> · 图钉为近似位置</div></>;
}

