FROM docker.elastic.co/elasticsearch/elasticsearch-wolfi:9.5.4
COPY --chown=1000:0 deploy/analysis-ik-9.5.4.zip /tmp/analysis-ik.zip
RUN bin/elasticsearch-plugin install --batch file:///tmp/analysis-ik.zip \
    && bin/elasticsearch-plugin install --batch analysis-kuromoji \
    && rm /tmp/analysis-ik.zip
