export const languages = [
 {code:'zh',name:'简体中文',short:'中文'}, {code:'en',name:'English',short:'EN'},
 {code:'es',name:'Español',short:'ES'}, {code:'fr',name:'Français',short:'FR'},
 {code:'ja',name:'日本語',short:'日本語'},
] as const;
export type ActiveLocale = typeof languages[number]['code'];
export const feedbackLabels:Record<ActiveLocale,{
 report:string;supplement:string;title:string;supplementTitle:string;context:string;original:string;meaning:string;
 chooseMeaning:string;reason:string;reasonHint:string;suggestion:string;suggestionHint:string;source:string;sourceHint:string;
 send:string;sending:string;success:string;error:string;done:string;cancel:string;reasonRequired:string;invalidSource:string;
}>={
 zh:{report:'释义有误？反馈',supplement:'补充释义',title:'反馈字面含义',supplementTitle:'补充字面含义',context:'地点',original:'原名',meaning:'当前释义',chooseMeaning:'选择要反馈的释义',reason:'哪里不对？',reasonHint:'请说明问题，方便我们核对。',suggestion:'建议的释义（选填）',suggestionHint:'你认为更合适的解释',source:'参考链接（选填）',sourceHint:'https://',send:'提交反馈',sending:'提交中…',success:'已收到反馈，感谢你帮助核对地名。',error:'提交失败，请重试；已填写的内容会保留。',done:'完成',cancel:'取消',reasonRequired:'请填写问题描述。',invalidSource:'请填写以 http:// 或 https:// 开头的有效链接，或留空。'},
 en:{report:'Meaning wrong? Send feedback',supplement:'Suggest a meaning',title:'Report a meaning',supplementTitle:'Suggest a literal meaning',context:'Place',original:'Original name',meaning:'Current meaning',chooseMeaning:'Which meaning?',reason:'What is wrong?',reasonHint:'Describe the issue so we can check it.',suggestion:'Suggested meaning (optional)',suggestionHint:'What would be more accurate?',source:'Source link (optional)',sourceHint:'https://',send:'Send feedback',sending:'Sending…',success:'Feedback received. Thank you for helping us check this name.',error:'Could not send feedback. Your text is still here; please try again.',done:'Done',cancel:'Cancel',reasonRequired:'Please describe the issue.',invalidSource:'Enter a valid http:// or https:// link, or leave this blank.'},
 es:{report:'¿Significado incorrecto? Avisar',supplement:'Sugerir un significado',title:'Informar de un significado',supplementTitle:'Sugerir un significado literal',context:'Lugar',original:'Nombre original',meaning:'Significado actual',chooseMeaning:'¿Qué significado?',reason:'¿Qué está mal?',reasonHint:'Describe el problema para que podamos revisarlo.',suggestion:'Significado propuesto (opcional)',suggestionHint:'¿Cuál sería más preciso?',source:'Enlace de referencia (opcional)',sourceHint:'https://',send:'Enviar',sending:'Enviando…',success:'Hemos recibido tus comentarios. Gracias por ayudarnos a revisar este nombre.',error:'No se pudo enviar. El texto se ha conservado; inténtalo de nuevo.',done:'Listo',cancel:'Cancelar',reasonRequired:'Describe el problema.',invalidSource:'Introduce un enlace válido que empiece por http:// o https://, o déjalo vacío.'},
 fr:{report:'Sens incorrect ? Signaler',supplement:'Suggérer un sens',title:'Signaler un sens',supplementTitle:'Suggérer un sens littéral',context:'Lieu',original:'Nom d’origine',meaning:'Sens actuel',chooseMeaning:'Quel sens ?',reason:'Quel est le problème ?',reasonHint:'Décrivez le problème pour que nous puissions le vérifier.',suggestion:'Sens proposé (facultatif)',suggestionHint:'Quel sens serait plus juste ?',source:'Lien de référence (facultatif)',sourceHint:'https://',send:'Envoyer',sending:'Envoi…',success:'Avis reçu. Merci de nous aider à vérifier ce nom.',error:'Envoi impossible. Votre texte est conservé ; veuillez réessayer.',done:'Terminé',cancel:'Annuler',reasonRequired:'Décrivez le problème.',invalidSource:'Saisissez un lien valide commençant par http:// ou https://, ou laissez ce champ vide.'},
 ja:{report:'意味が違う？報告する',supplement:'意味を提案する',title:'字面の意味を報告',supplementTitle:'字面の意味を提案',context:'地点',original:'元の地名',meaning:'現在の意味',chooseMeaning:'報告する意味',reason:'どこが違いますか？',reasonHint:'確認できるよう、問題を説明してください。',suggestion:'提案する意味（任意）',suggestionHint:'より適切な意味',source:'参考リンク（任意）',sourceHint:'https://',send:'送信',sending:'送信中…',success:'報告を受け付けました。地名の確認にご協力いただきありがとうございます。',error:'送信できませんでした。入力内容は残っています。再試行してください。',done:'完了',cancel:'キャンセル',reasonRequired:'問題の内容を入力してください。',invalidSource:'http:// または https:// で始まる有効なリンクを入力するか、空欄にしてください。'},
};
export const vectorLabels:Record<ActiveLocale,{matchMode:string;textMatch:string;vectorMatch:string;textShort:string;vectorShort:string;experimental:string;threshold:string;noVector:string;score:string}>={
 zh:{matchMode:'匹配方式',textMatch:'文本匹配',vectorMatch:'向量相似',textShort:'文本',vectorShort:'向量',experimental:'向量相近 · 试验',threshold:'相似度门槛',noVector:'该地点暂无当前语言向量',score:'相似度'},
 en:{matchMode:'Matching method',textMatch:'Text matching',vectorMatch:'Vector similarity',textShort:'Text',vectorShort:'Vector',experimental:'Vector similarity · Experimental',threshold:'Similarity threshold',noVector:'No vector for this place in the current language',score:'Similarity'},
 es:{matchMode:'Método de búsqueda',textMatch:'Coincidencia de texto',vectorMatch:'Similitud vectorial',textShort:'Texto',vectorShort:'Vector',experimental:'Similitud vectorial · Experimental',threshold:'Umbral de similitud',noVector:'Este lugar no tiene vector en el idioma actual',score:'Similitud'},
 fr:{matchMode:'Méthode de recherche',textMatch:'Correspondance textuelle',vectorMatch:'Similarité vectorielle',textShort:'Texte',vectorShort:'Vecteur',experimental:'Similarité vectorielle · Expérimental',threshold:'Seuil de similarité',noVector:'Aucun vecteur pour ce lieu dans la langue actuelle',score:'Similarité'},
 ja:{matchMode:'照合方法',textMatch:'テキスト照合',vectorMatch:'ベクトル類似',textShort:'テキスト',vectorShort:'ベクトル',experimental:'ベクトル類似 · 試験版',threshold:'類似度のしきい値',noVector:'この言語のベクトルはまだありません',score:'類似度'},
};
export type Locale = ActiveLocale | 'ko';
export const relatedListLabels:Record<Locale,{back:string}>={
 zh:{back:'返回探索'},
 en:{back:'Back to explore'},
 ja:{back:'探索に戻る'},
 fr:{back:'Retour à l’exploration'},
 es:{back:'Volver a explorar'},
 ko:{back:'탐색으로 돌아가기'},
};
export const isLocale = (value:unknown):value is ActiveLocale => languages.some(l=>l.code===value);
const en = {
 language:'Language',search:'Search places or meanings',submit:'Search',clear:'Clear search',open:'Open sidebar',close:'Close sidebar',
 eyebrow:'A MAP OF LITERAL MEANINGS',headline:'The world has fewer names than you think.',intro:'Different names, shared meanings. Discover unexpected connections between places.',
 explore:'Explore by meaning',all:'All {count} places',places:'{count} places',related:'{count} related places',results:'Search results',current:'Current exploration',
 loading:'Loading places…',searching:'Searching meanings…',searchLabel:'Name and meaning search',retry:'Try again',more:'Show more ({shown} / {total})',
 loadError:'Places could not be loaded. Please try again.',searchError:'Search is unavailable. Please try again.',empty:'No matching places yet',hint:'Try “new settlement”, “capital” or “Naples”. Meaning search currently covers our curated concepts.',
 searchTotal:'Showing {shown} of {total} results. Refine your search for more specific results.',negative:'Negative conditions are not supported yet. Describe the meaning you want to find.',
 footer:'A growing map of names.',sources:'Sources',exploring:'Exploring',wait:'Please wait…',allNames:'All names',scope:'Meaning match',exact:'Same meaning',near:'Related',theme:'Theme',
 fit:'Show all related places',lines:'Show connections',themeLines:'Connections are hidden in theme view',map:'Explore the map',
 lookup:'Map place',lookupLoading:'Looking up this place…',notFound:'This place has not been added yet.',ambiguous:'This place has conflicting data links.',unsupported:'This map label cannot be linked yet.',lookupError:'Could not look up this place. Please try again.',
 closeDetail:'Close place details',literal:'Literal meaning',noMeaning:'No literal meaning yet',original:'Original name',fallback:'Translation unavailable in this language · Showing {language}',
 same:'Same meaning',similar:'Related meaning',shared:'Shared theme',direction:'Related meaning · Different direction',selected:'Selected place',nameMatch:'Name match',meaningMatch:'Meaning match',
 globe:'Zoom out to the globe',streets:'Zoom to the selected place',mapPlaces:'Places on the map',keyboardHint:'Explore these places, or use the sidebar and search.',
 offline:'Street map unavailable. Showing the simplified globe.',mapError:'Some map resources could not be loaded. Please refresh.',zoomIn:'Zoom in',zoomOut:'Zoom out',
};
type Messages = {[K in keyof typeof en]:string};
export type MessageKey=keyof Messages;
export const messages:Record<Locale,Messages>={en,
 zh:{language:'语言',search:'搜索地名或含义',submit:'搜索',clear:'清空搜索',open:'展开侧栏',close:'收起侧栏',eyebrow:'名字里的世界',headline:'世界上的名字，比你想象的更相近。',intro:'名字不同，意思也许相同。发现地名背后的意外联系。',explore:'按含义探索',all:'全部 {count} 个地点',places:'{count} 个地点',related:'{count} 个关联地点',results:'搜索结果',current:'当前探索',loading:'正在加载地点…',searching:'正在查找相关含义…',searchLabel:'名称与含义搜索',retry:'重试',more:'显示更多（{shown} / {total}）',loadError:'地点数据暂时无法加载，请重试。',searchError:'搜索暂时不可用，请重试。',empty:'还没有找到相关名字',hint:'试试「新的定居点」「首都」或「Naples」。含义搜索暂时覆盖已收录的语义概念。',searchTotal:'共 {total} 条，显示前 {shown} 条；可缩小搜索范围。',negative:'暂不支持否定条件，请描述想查找的含义。',footer:'一份不断生长的名字地图。',sources:'资料来源',exploring:'正在探索',wait:'请稍候…',allNames:'所有名字',scope:'语义匹配范围',exact:'同义',near:'相近',theme:'主题',fit:'查看全部关联地点',lines:'显示语义连线',themeLines:'主题关联不绘制连线',map:'地图探索',lookup:'地图地点',lookupLoading:'正在查询地点…',notFound:'暂未收录这个地点的资料。',ambiguous:'这个地点的资料关联有冲突。',unsupported:'这个底图地名暂不支持直接关联。',lookupError:'地点查询失败，请重试。',closeDetail:'关闭地点详情',literal:'字面含义',noMeaning:'尚未收录字面含义',original:'原名',fallback:'当前语言暂无翻译 · 显示{language}',same:'同义归一',similar:'相近含义',shared:'共同主题',direction:'相近含义 · 方位不同',selected:'当前地点',nameMatch:'名称匹配',meaningMatch:'字面含义匹配',globe:'缩小到地球',streets:'放大到所选地点街区',mapPlaces:'地图地点，键盘选择',keyboardHint:'当前探索的地点；更多地点可使用侧栏或搜索。',offline:'街道底图连接失败，暂时显示简化地球。',mapError:'部分地图资源无法加载，请刷新重试。',zoomIn:'放大',zoomOut:'缩小'},
 es:{language:'Idioma',search:'Buscar lugares o significados',submit:'Buscar',clear:'Borrar búsqueda',open:'Abrir panel',close:'Cerrar panel',eyebrow:'UN MAPA DE SIGNIFICADOS LITERALES',headline:'El mundo tiene menos nombres de los que imaginas.',intro:'Nombres distintos, significados compartidos. Descubre conexiones inesperadas entre lugares.',explore:'Explorar por significado',all:'Los {count} lugares',places:'{count} lugares',related:'{count} lugares relacionados',results:'Resultados',current:'Exploración actual',loading:'Cargando lugares…',searching:'Buscando significados…',searchLabel:'Búsqueda de nombres y significados',retry:'Reintentar',more:'Mostrar más ({shown} / {total})',loadError:'No se pudieron cargar los lugares. Inténtalo de nuevo.',searchError:'La búsqueda no está disponible. Inténtalo de nuevo.',empty:'No se encontraron lugares',hint:'Prueba «new settlement», «capital» o «Naples». La búsqueda semántica cubre los conceptos de nuestra colección.',searchTotal:'Se muestran {shown} de {total} resultados. Acota la búsqueda.',negative:'Aún no se admiten condiciones negativas. Describe el significado que buscas.',footer:'Un mapa de nombres en constante crecimiento.',sources:'Fuentes',exploring:'Explorando',wait:'Espera un momento…',allNames:'Todos los nombres',scope:'Coincidencia semántica',exact:'Igual',near:'Similar',theme:'Tema',fit:'Ver todos los lugares relacionados',lines:'Mostrar conexiones',themeLines:'Las conexiones se ocultan en la vista temática',map:'Explorar el mapa',lookup:'Lugar del mapa',lookupLoading:'Consultando el lugar…',notFound:'Este lugar aún no se ha añadido.',ambiguous:'Este lugar tiene enlaces de datos contradictorios.',unsupported:'Esta etiqueta aún no puede vincularse.',lookupError:'No se pudo consultar el lugar. Inténtalo de nuevo.',closeDetail:'Cerrar detalles',literal:'Significado literal',noMeaning:'Aún no hay significado literal',original:'Nombre original',fallback:'Traducción no disponible · Mostrando {language}',same:'Mismo significado',similar:'Significado relacionado',shared:'Tema compartido',direction:'Significado similar · Dirección distinta',selected:'Lugar seleccionado',nameMatch:'Coincidencia de nombre',meaningMatch:'Coincidencia de significado',globe:'Ver el globo',streets:'Acercar al lugar seleccionado',mapPlaces:'Lugares del mapa',keyboardHint:'Explora estos lugares o usa el panel y la búsqueda.',offline:'Mapa de calles no disponible. Se muestra el globo simplificado.',mapError:'No se pudieron cargar algunos recursos del mapa. Actualiza la página.',zoomIn:'Acercar',zoomOut:'Alejar'},
 fr:{language:'Langue',search:'Rechercher un lieu ou un sens',submit:'Rechercher',clear:'Effacer la recherche',open:'Ouvrir le panneau',close:'Fermer le panneau',eyebrow:'UNE CARTE DES SENS LITTÉRAUX',headline:'Le monde a moins de noms que vous ne le pensez.',intro:'Des noms différents, des sens partagés. Découvrez des liens inattendus entre les lieux.',explore:'Explorer par sens',all:'Tous les lieux ({count})',places:'{count} lieux',related:'{count} lieux associés',results:'Résultats',current:'Exploration actuelle',loading:'Chargement des lieux…',searching:'Recherche de sens…',searchLabel:'Recherche par nom et par sens',retry:'Réessayer',more:'Voir plus ({shown} / {total})',loadError:'Impossible de charger les lieux. Réessayez.',searchError:'La recherche est indisponible. Réessayez.',empty:'Aucun lieu correspondant',hint:'Essayez «new settlement», «capital» ou «Naples». La recherche sémantique couvre les concepts de notre collection.',searchTotal:'{shown} résultats sur {total}. Affinez votre recherche.',negative:'Les conditions négatives ne sont pas encore prises en charge. Décrivez le sens recherché.',footer:'Une carte des noms qui ne cesse de grandir.',sources:'Sources',exploring:'Exploration',wait:'Veuillez patienter…',allNames:'Tous les noms',scope:'Correspondance sémantique',exact:'Identique',near:'Proche',theme:'Thème',fit:'Voir tous les lieux associés',lines:'Afficher les liens',themeLines:'Les liens sont masqués dans la vue thématique',map:'Explorer la carte',lookup:'Lieu sur la carte',lookupLoading:'Recherche du lieu…',notFound:'Ce lieu n’a pas encore été ajouté.',ambiguous:'Les liens de données de ce lieu sont contradictoires.',unsupported:'Cette étiquette ne peut pas encore être associée.',lookupError:'Impossible de trouver ce lieu. Réessayez.',closeDetail:'Fermer les détails',literal:'Sens littéral',noMeaning:'Aucun sens littéral renseigné',original:'Nom d’origine',fallback:'Traduction indisponible · Affiché en {language}',same:'Même sens',similar:'Sens proche',shared:'Thème commun',direction:'Sens proche · Direction différente',selected:'Lieu sélectionné',nameMatch:'Nom correspondant',meaningMatch:'Sens correspondant',globe:'Voir le globe',streets:'Zoomer sur le lieu sélectionné',mapPlaces:'Lieux sur la carte',keyboardHint:'Explorez ces lieux ou utilisez le panneau et la recherche.',offline:'Fond de carte indisponible. Affichage du globe simplifié.',mapError:'Certaines ressources de la carte sont indisponibles. Actualisez la page.',zoomIn:'Zoom avant',zoomOut:'Zoom arrière'},
 ja:{language:'言語',search:'地名や意味を検索',submit:'検索',clear:'検索をクリア',open:'サイドバーを開く',close:'サイドバーを閉じる',eyebrow:'地名の意味をめぐる地図',headline:'世界の地名は、思ったより似ている。',intro:'名前は違っても、意味は同じかもしれません。地名の意外なつながりを探しましょう。',explore:'意味から探す',all:'すべての地点（{count}）',places:'{count} 地点',related:'関連する {count} 地点',results:'検索結果',current:'探索中の地点',loading:'地点を読み込み中…',searching:'意味を検索中…',searchLabel:'地名と意味の検索',retry:'再試行',more:'さらに表示（{shown} / {total}）',loadError:'地点を読み込めませんでした。再試行してください。',searchError:'検索できません。再試行してください。',empty:'一致する地名がありません',hint:'「new settlement」「capital」「Naples」などをお試しください。意味検索は収録済みの概念に対応しています。',searchTotal:'{total} 件中 {shown} 件を表示。検索条件を絞り込めます。',negative:'否定条件には未対応です。探したい意味を入力してください。',footer:'地名の世界を、少しずつ広げる地図。',sources:'出典',exploring:'探索中',wait:'お待ちください…',allNames:'すべての地名',scope:'意味の一致範囲',exact:'同じ意味',near:'近い意味',theme:'テーマ',fit:'関連地点をすべて表示',lines:'つながりを表示',themeLines:'テーマ表示では線を表示しません',map:'地図を探索',lookup:'地図上の地点',lookupLoading:'地点を検索中…',notFound:'この地点の情報は未収録です。',ambiguous:'この地点のデータの対応関係に矛盾があります。',unsupported:'この地名はまだ直接関連付けられません。',lookupError:'地点の検索に失敗しました。再試行してください。',closeDetail:'地点の詳細を閉じる',literal:'字面の意味',noMeaning:'字面の意味は未収録です',original:'元の地名',fallback:'この言語の翻訳は未収録 · {language}で表示',same:'同じ意味',similar:'近い意味',shared:'共通のテーマ',direction:'近い意味 · 方角が異なる',selected:'選択中の地点',nameMatch:'地名が一致',meaningMatch:'意味が一致',globe:'地球全体を表示',streets:'選択地点を拡大',mapPlaces:'地図の地点',keyboardHint:'地点を選ぶか、サイドバーや検索をご利用ください。',offline:'道路地図を取得できないため、簡易地球を表示しています。',mapError:'一部の地図データを取得できません。再読み込みしてください。',zoomIn:'拡大',zoomOut:'縮小'},
 ko:{language:'언어',search:'지명이나 의미 검색',submit:'검색',clear:'검색 지우기',open:'사이드바 열기',close:'사이드바 닫기',eyebrow:'지명의 뜻을 담은 지도',headline:'세계의 지명은 생각보다 서로 닮아 있습니다.',intro:'이름은 달라도 의미는 같을 수 있습니다. 지명 사이의 뜻밖의 연결을 찾아보세요.',explore:'의미로 둘러보기',all:'전체 {count}개 장소',places:'장소 {count}개',related:'관련 장소 {count}개',results:'검색 결과',current:'현재 탐색',loading:'장소 불러오는 중…',searching:'의미 검색 중…',searchLabel:'이름 및 의미 검색',retry:'다시 시도',more:'더 보기 ({shown} / {total})',loadError:'장소를 불러올 수 없습니다. 다시 시도하세요.',searchError:'검색할 수 없습니다. 다시 시도하세요.',empty:'일치하는 지명이 없습니다',hint:'“new settlement”, “capital”, “Naples”를 검색해 보세요. 의미 검색은 수록된 개념을 지원합니다.',searchTotal:'{total}개 중 {shown}개 표시. 검색 범위를 좁혀 보세요.',negative:'부정 조건은 아직 지원하지 않습니다. 찾는 의미를 입력하세요.',footer:'계속 자라나는 지명 지도.',sources:'출처',exploring:'탐색 중',wait:'잠시 기다려 주세요…',allNames:'모든 지명',scope:'의미 일치 범위',exact:'같은 뜻',near:'비슷한 뜻',theme:'주제',fit:'관련 장소 모두 보기',lines:'연결선 표시',themeLines:'주제 보기에서는 연결선을 숨깁니다',map:'지도 탐색',lookup:'지도상의 장소',lookupLoading:'장소 조회 중…',notFound:'아직 수록되지 않은 장소입니다.',ambiguous:'이 장소의 데이터 연결이 일치하지 않습니다.',unsupported:'이 지명은 아직 직접 연결할 수 없습니다.',lookupError:'장소 조회에 실패했습니다. 다시 시도하세요.',closeDetail:'장소 정보 닫기',literal:'이름의 문자적 의미',noMeaning:'아직 의미가 수록되지 않았습니다',original:'원래 이름',fallback:'이 언어의 번역이 없습니다 · {language} 표시',same:'같은 의미',similar:'비슷한 의미',shared:'공통 주제',direction:'비슷한 의미 · 다른 방향',selected:'선택한 장소',nameMatch:'이름 일치',meaningMatch:'의미 일치',globe:'지구 전체 보기',streets:'선택한 장소 확대',mapPlaces:'지도상의 장소',keyboardHint:'장소를 선택하거나 사이드바와 검색을 이용하세요.',offline:'도로 지도를 불러올 수 없어 간략한 지구를 표시합니다.',mapError:'일부 지도 데이터를 불러올 수 없습니다. 새로고침해 주세요.',zoomIn:'확대',zoomOut:'축소'},
};
export function translate(locale:Locale,key:MessageKey,params:Record<string,string|number>={}){
 const singular:Partial<Record<Locale,Partial<Record<MessageKey,string>>>>={en:{places:'1 place',related:'1 related place'},fr:{places:'1 lieu',related:'1 lieu associé'},es:{places:'1 lugar',related:'1 lugar relacionado'}};
 const template=(params.count===1&&singular[locale]?.[key])||messages[locale][key];
 return template.replace(/\{(\w+)\}/g,(_,key)=>String(params[key]??`{${key}}`));
}
export function localizedText(values:Partial<Record<string,string>>,locale:Locale):{text:string;lang:string}|null{
 const exact=values[locale]||(locale==='zh'?(values['zh-Hans']||values['zh-CN']):undefined);
 if(exact)return {text:exact,lang:locale};
 const fallback=['en','und','zh',...Object.keys(values)].find(lang=>values[lang]?.trim());
 return fallback?{text:values[fallback]!,lang:fallback}:null;
}
export function languageName(code:string,locale:Locale){
 try{return new Intl.DisplayNames([locale],{type:'language'}).of(code)||code;}catch{return code;}
}
const collectionNames:Record<Locale,string[]>={en:['New City','White City','Capital','Center','New beginnings'],zh:['新城','白城','都城','中心与都城','名字里的新'],es:['Ciudad nueva','Ciudad blanca','Capital','Centro','Nuevos comienzos'],fr:['Ville nouvelle','Ville blanche','Capitale','Centre','Nouveaux départs'],ja:['新しい街','白い街','都','中心と都','新たな始まり'],ko:['새로운 도시','하얀 도시','수도','중심과 수도','새로운 시작']};
export function collectionName(id:string,locale:Locale){const index=['new-settlement','white-settlement','capital-family','centrality','newness'].indexOf(id);return index<0?messages[locale].allNames:collectionNames[locale][index];}
const kindKeys=['country','city','metropolis','ancient_city','town','village','river','lake','sea','ocean','mountain','island','hamlet','suburb','municipality','atoll','locality'];
const kinds:Record<Locale,string[]>={en:['Country','City','Metropolis','Ancient city','Town','Village','River','Lake','Sea','Ocean','Mountain','Island','Hamlet','Suburb','Municipality','Atoll','Locality'],zh:['国家','城市','城市','古城','城镇','村庄','河流','湖泊','海域','海洋','山','岛屿','村落','城区','市镇','环礁','地点'],es:['País','Ciudad','Metrópolis','Ciudad antigua','Localidad','Aldea','Río','Lago','Mar','Océano','Montaña','Isla','Caserío','Barrio','Municipio','Atolón','Lugar'],fr:['Pays','Ville','Métropole','Ville antique','Bourg','Village','Fleuve','Lac','Mer','Océan','Montagne','Île','Hameau','Quartier','Commune','Atoll','Localité'],ja:['国','都市','大都市','古代都市','町','村','川','湖','海','大洋','山','島','集落','地区','自治体','環礁','地点'],ko:['국가','도시','대도시','고대 도시','마을','촌락','강','호수','바다','대양','산','섬','작은 마을','교외','지방 자치체','환초','장소']};
const regionKindName:Record<Locale,string>={en:'Administrative region',zh:'省级行政区',es:'Región administrativa',fr:'Région administrative',ja:'省級行政区',ko:'광역 행정구역'};
export function kindName(kind:string,locale:Locale){if(kind==='state'||kind==='province')return regionKindName[locale];const i=kindKeys.indexOf(kind);return i<0?kind:kinds[locale][i];}
export function relationText(value:string,locale:Locale){return translate(locale,({'当前地点':'selected','同义归一':'same','相近含义 · 方位不同':'direction','共同主题':'shared'} as Record<string,MessageKey>)[value]||'similar');}
